/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.exec.proto.beans;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class StringList implements Externalizable, Message<StringList>, Schema<StringList>
{

    public static Schema<StringList> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static StringList getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final StringList DEFAULT_INSTANCE = new StringList();

    
    private List<String> list;

    public StringList()
    {
        
    }

    // getters and setters

    // list

    public List<String> getListList()
    {
        return list;
    }

    public StringList setListList(List<String> list)
    {
        this.list = list;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<StringList> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public StringList newMessage()
    {
        return new StringList();
    }

    public Class<StringList> typeClass()
    {
        return StringList.class;
    }

    public String messageName()
    {
        return StringList.class.getSimpleName();
    }

    public String messageFullName()
    {
        return StringList.class.getName();
    }

    public boolean isInitialized(StringList message)
    {
        return true;
    }

    public void mergeFrom(Input input, StringList message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    if(message.list == null)
                        message.list = new ArrayList<String>();
                    message.list.add(input.readString());
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, StringList message) throws IOException
    {
        if(message.list != null)
        {
            for(String list : message.list)
            {
                if(list != null)
                    output.writeString(1, list, true);
            }
        }
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "list";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("list", 1);
    }
    
}
