/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.exec.proto.beans;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class UDFHolder implements Externalizable, Message<UDFHolder>, Schema<UDFHolder>
{

    public static Schema<UDFHolder> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static UDFHolder getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final UDFHolder DEFAULT_INSTANCE = new UDFHolder();

    
    private JarHolder binary;
    private JarHolder source;

    public UDFHolder()
    {
        
    }

    public UDFHolder(
        JarHolder binary,
        JarHolder source
    )
    {
        this.binary = binary;
        this.source = source;
    }

    // getters and setters

    // binary

    public JarHolder getBinary()
    {
        return binary;
    }

    public UDFHolder setBinary(JarHolder binary)
    {
        this.binary = binary;
        return this;
    }

    // source

    public JarHolder getSource()
    {
        return source;
    }

    public UDFHolder setSource(JarHolder source)
    {
        this.source = source;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<UDFHolder> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public UDFHolder newMessage()
    {
        return new UDFHolder();
    }

    public Class<UDFHolder> typeClass()
    {
        return UDFHolder.class;
    }

    public String messageName()
    {
        return UDFHolder.class.getSimpleName();
    }

    public String messageFullName()
    {
        return UDFHolder.class.getName();
    }

    public boolean isInitialized(UDFHolder message)
    {
        return 
            message.binary != null 
            && message.source != null;
    }

    public void mergeFrom(Input input, UDFHolder message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.binary = input.mergeObject(message.binary, JarHolder.getSchema());
                    break;

                case 2:
                    message.source = input.mergeObject(message.source, JarHolder.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, UDFHolder message) throws IOException
    {
        if(message.binary == null)
            throw new UninitializedMessageException(message);
        output.writeObject(1, message.binary, JarHolder.getSchema(), false);


        if(message.source == null)
            throw new UninitializedMessageException(message);
        output.writeObject(2, message.source, JarHolder.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "binary";
            case 2: return "source";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("binary", 1);
        __fieldMap.put("source", 2);
    }
    
}
